MifosOptions:
  baseUrl: 'https://demo.openmf.org/mifosng-provider/api/v1'
  tenantId: default
  user: mifos
  pass: password
MessageSender:
  class: Sol4MobSender
  options:
    uri: 'http://demo3275.sms-providers.com'
    username: 'walter@resilientsystems.co'
    password: '060A31AD'
MessageSignature: ' - Regards, MxMessenger'
