MifosOptions:
  baseUrl: 'https://demo.openmf.org/mifosng-provider/api/v1'
  tenantId: default
  user: mifos
  pass: password
MessageSender:
  class: EBulkSMSSender
  options:
    uri: 'http://api.ebulksms.com:8080/sendsms'
    username: # you TBulkSMS customerid
    apikey: # your TBulkSMS API key
    flash: 0
    sender: Mifos
